prop-set lcsim.detector HPS-PhysicsRun2016-Pass2
prop-set lcsim.steering /org/hps/steering/recon/PhysicsRun2016FullRecon_RemoteAida.lcsim
prop-set lcsim.run 7799
prop-set lcsim.conditions jdbc:sqlite:/work/slac/data/conditions/hps_conditions_2020_08_17.db
prop-set lcsim.maxEvents 10000
prop-set lcsim.freeze true
prop-set lcsim.builder org.hps.evio.LCSimTestRunEventBuilder
prop-set station.queue 1 
prop-set station.stopOnErrors true
prop-set station.stopOnEndRun true
prop-set station.printInterval 1
prop-set station.loggingConfig ../../station_logging.properties
prop-set et.buffer /tmp/ETBuffer
prop-set et.host localhost
prop-set et.port 11111
prop-set et.logLevel 4
prop-set et.waitTime 0
prop-set et.mode 0
prop-set et.chunk 1
prop-set et.prescale 1
prop-set et.connectionAttempts 10

create -s 4
